- changelog/39.feature.rst
- dbt_sugar/core/config/config.py
- dbt_sugar/core/exceptions.py
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- tests/config_test.py
- tests/sugar_config.yml
- tests/sugar_config_missing_default.yml
Sugar cane could be a bit loaded as a reference so I'm turning to a less loaded concept called `syrup` it's also sweeter 🍬 
unit tests are running locally.
Closes #35
> refactor: rename all references to sugar cane and cane to syrup

- dbt_sugar/core/clients/dbt.py
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- dbt_sugar/core/task/base.py
- dbt_sugar/core/task/doc.py
- tests/docker_postgres/profiles.yml
- tests/handle_test.py
- In order to test profiles in CI we need to allow for a `--profile-dir` argument to be passed. This is now done.
- I also updated the behaviour and expectation of the unit test for `handle()` since we don't want it to run any of the documentation task. This might be something we revisit more cleanly later it's a bit "dirty" but it will get us there.
Unit tests are now passing locally
> refactor: allow for profiles-dir argument and change handle test assumptions

- .isort.cfg
- .pre-commit-config.yaml
- changelog/46.feature.rst
- codecov.yml
- dbt_sugar/core/main.py
- dbt_sugar/core/ui/cli_ui.py
- poetry.lock
- pyproject.toml
- tests/cli_ui_test.py
- tests/config_test.py
- tests/doc_task_test.py
- tests/handle_test.py
- tests/postgres_test.py
- tests/snowflake_test.py
- tests/test_yaml_helpers.py
Adds the Front-End side of the `DocumentationTask` UI.
Defines the API contract between the front end and back end of the documentation task.
Orchestrate user input collection flow.
Tested interactively so far, need to see how we can similate user input in pytest to place unit tests all the code introduced in this PR.
Addresses the Front-End side of #44 
> feat: :lipstick: implement Documentation CLI UI

- .github/workflows/main_ci.yml
The `pull_request_target` trigger in GH actions exposes tokens: https://securitylab.github.com/research/github-actions-preventing-pwn-requests and https://www.youtube.com/watch?v=_fpXyS_i1xE
I had turned on this trigger to allow for forks to also be able to publish code coverage to codecov however they now (well for a while) provide tokenless report sending so this should be good.
> ci: use `pull_request` instead of `pull_request_target` to prevent pwn

- changelog/50.feature.rst
- dbt_sugar/core/ui/cli_ui.py
- pyproject.toml
- tests/cli_ui_test.py
Adds UI user input flow for already documented columns.
The API will expect the following input:
```python
question_type = 'documented_columns'
question_payload = [
{
"type": "checkbox",
"name": "cols_to_document",
"choices": {
"col_a": "Column a description",
"column_b": "Column b description",
},
"message": "Select the columns you want to document.",
}
]
c = UserInputCollector(question_type, question_payload)
c.collect()
```
and will return a response that looks like:
```python
{'col_a': 'New description'}
```
UI looks like this:
Unit tests are added and passing locally.
Partially addresses #44
> feat(ui): implement already document cols FE API

- dbt_sugar/core/clients/dbt.py
- dbt_sugar/core/config/config.py
- dbt_sugar/core/exceptions.py
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- pyproject.toml
- tests/config_test.py
- tests/dbt_client_test.py
- tests/doc_task_test.py
- tests/handle_test.py
- tests/profile_test.py
- tests/profiles.yml
- tests/test_yaml_helpers.py
In order for `dbt-sugar` to know which profile to choose in order to connect to a database it needs to read the profile name from dbt's `dbt_project.yml`.
- The `sugar_config.yml` contains a list (currently we only support one entry) of dbt projects under scope. This list is made of dicts which contain `name` and `path` of dbt projects.
- The `DbtProject` object then loads the `dbt_project.yml` file from it's provided path and stores the `profile_name` which will be provided to `DbtProfile`.
This PR also implements reading the correct `target` profile from the `profiles.yml` by either getting it from `--target` on the CLI or from the `target:` yaml field in `profiles.yml`. Priority is given to the CLI argument as it is "closer" to the user.
I modified the unit tests to work and it seems …
> feat: parse profile name from dbt_project

- .isort.cfg
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- dbt_sugar/core/ui/traceback_manager.py
- poetry.lock
- pyproject.toml
Adds some colours to the logo and also allow number of elements in the stack trace to be controlled by a `-v` / `--verbose` CLI option
No tests required so long as it looks good :)
> refactor: make logo coloured and fix traceback depth options

- changelog/86.feature.rst
- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
This code change adds support for tags addition.
When documenting a column a user will now be asked whether they want to add tags to this column. If they do, we ask them to provide a comma separated list of strings for those tags.
The UI API will return the following payload to the backend:
```python
{
'col_a': {
'description': 'Description for col a',
'tests': ['unique'],
'tags': ['PII']
},
'col_b': {'description': 'Description for col b'}
}
```
Unit tests were modified to account for and test for tag generation in the payload
Closes #62
> feat: implement UI for tags

- .github/workflows/pr_lint.yml
- changelog/93.feature.rst
- dbt_sugar/core/config/config.py
- dbt_sugar/core/exceptions.py
- tests/config_test.py
- tests/sugar_config.yml
Implements an explicit error raising for the intentional regression proposed in [#92](https://github.com/bitpicky/dbt-sugar/issues/92)
TLDR: We cannot support (for now) having more than one dbt project under dbt-sugar's scope given the current backend design and we're making a concious choice to implement this regression for the time being so that we can get some testing and usage sonner.
Since the `sugar_config.yml` field that stores the dbt project information is pluralised we want to make sure people do not add multiple projects for now and expect it to work although it would otherwise silently ignore a bunch of projects.
I developed the feature via TDD so the unit test covers this feature.
Does not implement or close any issue but is related to #92
(Ideally, all boxes are checked by …
> regr: implement explicit error for multiple dbt projects

- changelog/101.feature.rst
- dbt_sugar/core/config/config.py
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- dbt_sugar/core/task/doc.py
- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
- tests/config_test.py
- tests/doc_task_test.py
- tests/handle_test.py
- tests/test_dbt_project/dbt_sugar_test/models/example/schema.yml
Gives users control over whether dbt-sugar will ask for test enforcement or tag addition. This is achieved in the following ways:
- users can pass `--ask-for-tests/--no-ask-for-tests` to call test enforcement or not
- users can pass `--ask-for-tags/--no-ask-for-tags` to call tag addition or not
- users can add `always_enforce_tests` to each `syrup` in the `sugar_config.yml`. This will make dbt-sugar **always** ask for tests. If users do not provide this field, it is turned on by default. If it is set to `false` users will **have** to add `--ask-for-tests` on each run on the CLI to trigger tests enforcement.
- users can add `always_add_tags` similarly to what is explained above but for tags. Same default behaviour as above.
If a user has either (or both) of the `always_enforce_tests` and …
> feat: allow tag and test skipping from CLI and sugar_config

- dbt_sugar/core/task/doc.py
- tests/doc_task_test.py
Adds column entry list if the model doesn't have any in the schema.yml
Resolves this comment: https://github.com/bitpicky/dbt-sugar/issues/124#issuecomment-792289513
> fix: add columns when the model doesn't have any

- dbt_sugar/core/ui/cli_ui.py
The checking of the tags was incorrect because it was None, with the split it was a list of one empty element [""].
Resolves this comment: https://github.com/bitpicky/dbt-sugar/issues/124#issuecomment-793052758
> fix: do not add tags if user provided an empty string

- dbt_sugar/core/task/doc.py
As mentioned in #136 when a lot of tests pass the message that warns users that their test will not be added to the schema was a bit swamped and hard to notice.
Now the output will look like this:
```
[17:14:42] The unique test on 'customer_id' FAILED.                                                                                                                                                                                                                                            
└It will not be added to your schema.yml.  
```
Ran interactively.
Closes #136
> fix: make failed test output more salient

- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
- tests/doc_task_test.py
In order to properly terminate the app when users do `ctrl + c` we need to use `unsafe_ask()` from `questionary` so that the `KeyboardInterrupt` is not escaped by questionary and it bubbles up in our app scope so we can make the app do what we need in terms of cleaning if a user chooses to abort.
Resolves #142
> refactor: use unsafe_ask() instead of ask() in prompts

- dbt_sugar/core/task/audit.py
- dbt_sugar/core/task/doc.py
- tests/audit_task_test.py
- tests/doc_task_test.py
- tests/sugar_config.yml
- tests/test_dbt_project/jaffle_shop/models/marts/core/schema.yml
The model-level description prompt was always saying "do you want to change the model description" but that could lead to confusion when the user documents a model for the first time and there is no description to change.
Tested interactively and added unit test case for is_already_documented variable
Resolves #135
> fix: change model prompt question based on doc status

- dbt_sugar/core/task/doc.py
- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
- tests/sugar_config.yml
Resolves #152
It wasn't really clear to the user that we are giving them already documented columns to document 5 at a time. The `UserInputCollector` API was now changed to accept a `is_first_page` optional `bool` which enables the wording of the prompts to tell users whether they are getting something paginated and whether they are documenting the first page or next pages of columns.
> refactor: clarify pagination to users in undocumented cols flow

- dbt_sugar/core/task/doc.py
- tests/doc_task_test.py
Ensures that the model description is always the first element of the model dictionary in the schema.yml
Resolves #124 
> feat: adding ordering into saving content

- dbt_sugar/core/task/audit.py
Fixing the message to be more clear, and not printing statistics table if they are not columns.
Resolves #158 
> feat: not print anything if they are not columns

- dbt_sugar/core/task/audit.py
- tests/audit_task_test.py
Improves the following visual aspects of the audit task reports:
- Table title is now actually printing as the title (needed to explicitly pass the `title=` kwarg
- The word "Total" is not first-letter captialised
- The total line is now printed separately on model report instead of appended to the last column
Interactively and some of the test assumptions were modified to reflect the changes.
No issue
> refactor: :sparkles: improve audit look

- dbt_sugar/core/task/audit.py
- dbt_sugar/core/task/doc.py
When a test failed and was removed from the list the progress priting was missing some of the tests. This is because we're doing removal based on index
This PR makes a copy of the list so that it is always available to printing and leaves the removal of tests into the original list thereby retaining the intended behaviour but allowing for log printing.
Interactively
Resolves #156
> fix: ensure all test outputs print

- changelog/167.fix.rst
- dbt_sugar/core/task/doc.py
- tests/test_dbt_project/jaffle_shop/models/marts/core/schema.yml
- tests/test_dbt_project/jaffle_shop/models/staging/schema.yml
In #159 we implemented `OrderedDict` to ensure that we could explicitly control the order of the `name` and `description` keys but somehow we were destroying all that hard work by casting it to a regular `dict()` at return time.
This PR removes the cast and the schema yaml is in good order now.
Resolves #165
> fix: ensure model name and description is first

- .pre-commit-config.yaml
- changelog/173.fix.rst
- dbt_sugar/core/task/doc.py
- poetry.lock
- pyproject.toml
- tests/doc_task_test.py
The columns dict wasn't ordered and order wasn't guaranteed.
This is now explicitly done so we should be able to cover all the vases and isses we've encountered
Locally and updated the tests
Resolves #172
> fix: ensure columns dict is also ordered

- changelog/187.fix.rst
- dbt_sugar/core/task/base.py
- tests/test_dbt_project/jaffle_shop/packages.yml
dbt packages get installed inside of `dbt_modules` when running `dbt deps`. 
we now exclude it from the search path as dbt-sugar should never attempt to document or audit those folders.
Resolves #183
> fix: exclude dbt_modules from search path

- changelog/189.fix.rst
- dbt_sugar/core/config/config.py
- dbt_sugar/core/task/base.py
- dbt_sugar/core/task/doc.py
- tests/config_test.py
- tests/doc_task_test.py
- tests/sugar_config.yml
- tests/sugar_config_missing_default.yml
- implement model exclusion working for the audit task
- make app exit early when user tries to document an excluded table
Resolves #185
> fix: use excluded_tables info to skip excluded models

- .pre-commit-config.yaml
- changelog/193.feat.rst
- dbt_sugar/core/config/config.py
- dbt_sugar/core/task/audit.py
- dbt_sugar/core/task/base.py
- dbt_sugar/core/task/doc.py
- tests/audit_task_test.py
- tests/base_task_test.py
- tests/config_test.py
- tests/doc_task_test.py
- tests/sugar_config.yml
- tests/test_dbt_project/dbt_sugar_test/models/example/arbitrary_name.yml
- tests/test_dbt_project/dbt_sugar_test/models/example/my_first_dbt_model_excluded.sql
- tests/test_dbt_project/jaffle_shop/models/schema.yml
- tests/test_dbt_project/jaffle_shop/models/some_other.yml
- rename confusing global dict building functions
- remove orders from schema.yml
- add orders in another schema file with arbitrary name
- rework logic to find models in schema files to work with arbitrary names
Resolves #184
> feat: allow for arbitrarily named model property files

- dbt_sugar/core/task/base.py
While I was testing dbt-sugar was trying to read a schema.yml without models attribute and it was failing, so getting the models attribute with get.
> fix: use `.get()` when looking for model content in yml files

- changelog/205.fix.rst
- dbt_sugar/core/connectors/snowflake_connector.py
Looks like we forgot to pass the `warehouse` to the snowflake URL connector. We do now!
I cannot test against a snowflake warehouse sadly so hopefully someone will be able to help. Gonna see with @sphinks (the person who reported the bug if he can help)
Resolves #204
> fix: add warehouse parameter to snowflake URL creator

- changelog/194.feature_primary_key_tests.md
- changelog/203.feature.md
> fix: rename and rephrase news fragment

- dbt_sugar/core/connectors/base.py
- feat: add describe table logic in snowflake connector (#212)
- feat: automatic insertion of primary key tests (#203)
- add `use_describe` to the base `get_columns_from_table` def
Because we allow the `snowflake_connector.get_columns_from_table()` to take a `use_describe` we also add this parameter to the base so that the signatures are the same a less persmissive than if we allowed `**kwargs`.
> refactor: add use_describe to base

- changelog/239.feature.md
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
In #233 we added a new task called `bootstrap` which creates models and column placeholders. Users might want to make the audit task optionally call the bootstrap first which they can now do by calling audit with `--bootstrap`
Resolves #210
> feat: allow audit task to run bootstrap

- .isort.cfg
- changelog/238.feature.md
- dbt_sugar/core/task/doc.py
- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
- tests/doc_task_test.py
- tests/test_dbt_project/dbt_sugar_test/models/folder_to_exclude/schema.yml
Adding the ability to add custom tests and execute the tests with subprocess.
Things to have in mind:
- If the test is malformed all the tests that you add can not be checked, and as a result, they will not be added.
- The process of adding tests is really simple, we add all the tests we execute dbt test in the model, get the response and calculate which model is PASS and which FAIL or ERROR. We remove all the tests that the status is not PASS.
Ran it in local. 
Closes #65
> feat: collect rich user input for tests with subprocess

- .github/workflows/main_ci.yml
- changelog/257.fix.md
- dbt_sugar/core/task/bootstrap.py
- tests/bootstrap_task_test.py
A weird error happened in the CI only in GHAs. It was due to the files list not being sorted. Adding a `sorted()` on the list fixes the issue
Unit tests are now passing again.
> fix: sort files when building all models dict

- dbt_sugar/core/task/doc.py
Adding into dbt test the parameter project-dir so we are able to run the tests outside the project.
> fix: allow run dbt-sugar tests outside the project

- changelog/268.misc.md
- dbt_sugar/core/ui/cli_ui.py
- tests/cli_ui_test.py
The test prompt asking users whether they want to add complex or simple test was a bit confusing it is not (hopefully) less confusing
> feat: make complex tests prompts a bit more user friendly

- .isort.cfg
- changelog/275.misc.md
- dbt_sugar/core/logger.py
- poetry.lock
- pyproject.toml
The debug logger prints the dbt profile under context. This means passwords are exposed in the log file as well as the console (if running with "debug").
This PR implements log filtering via `logredactor` and hides the password from the log while still allowing for printing most of the profile for debug purposes.
Resolves #272
> feat: obfuscate logs from password

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- changelog/changelog/291.fix.md
- dbt_sugar/core/connectors/redshift_connector.py
Unable to connect to Redshift warehouse via autossh
```
(psycopg2.OperationalError) server certificate for "..redshift.amazonaws.com" does not match host name "localhost"
```
Adding the default `sslmode` per `psycopg2` [docs on SSL Connections](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L77)
I was able to test that this change allowed my `localhost` connection to Redshift to work. However, I cannot test if this will break other Redshift connector configurations.
> fix: add default sslmode to redshift connector engine

- changelog/309.fix.md
- dbt_sugar/core/clients/yaml_helpers.py
- dbt_sugar/core/main.py
- dbt_sugar/core/task/base.py
When we walk through yaml files, we basically process any kind of yaml unless they are in some folder exclusion that we know of or because users have specified to exclude some models from the dbt-sugar scope.
However, when we don't know we have to exclude the files we process it and we end up potentially changing its format and maybe even content?
This is kind of a "hot-fix" PR to get the feature out to a user in need, but we will want to overhaul the way we walk through and into files so that we don't end up processing a bunch of useless crap.
Tested locally, with random yaml file within the dbt model scope and working fine.
Resolves #294
(Ideally, all boxes are checked by the time we merged the PR, if you don't know how to do any of these don't hesitate to say so in the PR and we'll …
> fix: do not save yamls that do not contain models

- dbt_sugar/core/main.py
- poetry.lock
- pyproject.toml
Resolves #294
The CLI flag for `--preserve-yaml-order` was set to False which makes the CLI override actually override since it's logic is that if it's not None it will override the config argument.
- tested locally
Closes #294
> fix: set default preserve-yaml-order CLI flag to none

- changelog/348.fix.md
- dbt_sugar/core/flags.py
- dbt_sugar/core/main.py
- dbt_sugar/core/task/base.py
- pyproject.toml
This solves for profile target not being available in all commands and defaulting to the default profile. 
I personally ran it on my own dbt projects. 
Relevant issue #346
> fix: Profile target available to ALL commands
